### ISSUE TITLE
[bug]: Installing fuwa results in an error

### ISSUE THREAD

**Issue by ArtieFuzzz** [fuwa-org/fuwa#63]
### Problem description

It seems like the error is coming from the prepare script when I install `fuwa`

![despair](https://stackowoflow.com/X32HaNK8Lt.png)
I have also initiated a git repository within the project

### Reproduction steps

- Create a new project
- Install `fuwa`

### Expected behaviour

- It should install normally without any errors

### System information

- OS: Windows 10
- NodeJS: v17.8.0
- NPM and Yarn (classic and v3) were used

### Bug checklist

- [X] I can reproduce this continually
- [X] Others can reproduce this bug as well
- [X] This isn't an external issue with the Discord API

**Comment by splatterxl** [comment]
<s>Ah, this is probably because of me installing TypeScript beta while the other packages don't support it. I'll work on a fix.</s> Nope, it's something else.

Also please note that Fuwa __is not ready for production use__.

**Comment by splatterxl** [comment]
Should be fixed in 8f8deb2afd75e32466fad280717552c4783cefd7 and f3e16bad19aa791c0fc5c7e9d7e2912db81acd81.
